package com.sakurafuld.hyperdaimc.datagen;

import com.sakurafuld.hyperdaimc.content.HyperBlocks;
import com.sakurafuld.hyperdaimc.content.HyperItems;
import net.minecraft.data.PackOutput;
import net.minecraft.data.recipes.FinishedRecipe;
import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraftforge.common.Tags;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Consumer;

import static com.sakurafuld.hyperdaimc.infrastructure.Deets.identifier;

public class HyperRecipeProvider extends RecipeProvider {
    public HyperRecipeProvider(PackOutput pOutput) {
        super(pOutput);
    }

    @Override
    protected void buildRecipes(Consumer<FinishedRecipe> pWriter) {
        DeskShapelessRecipeBuilder.essence("ground")
                .values(ItemTags.DIRT, Tags.Items.SAND, Tags.Items.GRAVEL)
//                .exclusion(Items.MOSS_BLOCK)
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("crust")
                .values(Tags.Items.STONE, Tags.Items.COBBLESTONE, Tags.Items.SANDSTONE)
                .exclusion(Items.INFESTED_STONE, Items.INFESTED_COBBLESTONE, Items.INFESTED_DEEPSLATE, Items.POLISHED_ANDESITE, Items.POLISHED_DIORITE, Items.POLISHED_GRANITE, Items.POLISHED_DEEPSLATE)
                .exclusion(Items.CUT_SANDSTONE, Items.CHISELED_SANDSTONE, Items.SMOOTH_SANDSTONE, Items.CUT_RED_SANDSTONE, Items.CHISELED_RED_SANDSTONE, Items.SMOOTH_RED_SANDSTONE)
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("mineral")
                .values(Tags.Items.STORAGE_BLOCKS)
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("herb")
                .values(Tags.Items.SEEDS)
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("marine")
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("tree")
                .values(ItemTags.LOGS)
                .exclusion(Items.OAK_WOOD, Items.STRIPPED_OAK_LOG, Items.STRIPPED_OAK_WOOD, Items.SPRUCE_WOOD, Items.STRIPPED_SPRUCE_LOG, Items.STRIPPED_SPRUCE_WOOD, Items.STRIPPED_BIRCH_WOOD, Items.BIRCH_WOOD, Items.STRIPPED_BIRCH_LOG, Items.STRIPPED_BIRCH_WOOD, Items.JUNGLE_WOOD, Items.STRIPPED_JUNGLE_LOG, Items.STRIPPED_JUNGLE_WOOD, Items.ACACIA_WOOD, Items.STRIPPED_ACACIA_LOG, Items.STRIPPED_ACACIA_WOOD, Items.DARK_OAK_WOOD, Items.STRIPPED_DARK_OAK_LOG, Items.STRIPPED_DARK_OAK_WOOD, Items.CRIMSON_HYPHAE, Items.STRIPPED_CRIMSON_STEM, Items.STRIPPED_CRIMSON_HYPHAE, Items.WARPED_HYPHAE, Items.STRIPPED_WARPED_STEM, Items.STRIPPED_WARPED_HYPHAE)
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("food")
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("motion")
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("partition")
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("light")
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("shadow")
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("battle")
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("sound")
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("work")
                .saveMaterial(pWriter);
        DeskShapelessRecipeBuilder.essence("drawing")
                .saveMaterial(pWriter);

        DeskShapedRecipeBuilder.core("land")
                .pattern("  H  ")
                .pattern("HFHFH")
                .pattern("GGG!G")
                .pattern("GCGCG")
                .pattern("CCCCC")
                .define('H', HyperItems.getEssence("herb"))
                .define('F', HyperItems.getEssence("food"))
                .define('G', HyperItems.getEssence("ground"))
                .define('C', HyperItems.getEssence("crust"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("cave")
                .pattern("CCCCC")
                .pattern("CMCMC")
                .pattern("MSSSM")
                .pattern("CSSSC")
                .pattern("C!CMC")
                .define('C', HyperItems.getEssence("crust"))
                .define('M', HyperItems.getEssence("mineral"))
                .define('S', HyperItems.getEssence("shadow"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("forest")
                .pattern("  H  ")
                .pattern("HHH!H")
                .pattern("HTFTH")
                .pattern(" T T ")
                .pattern("MTMTM")
                .define('T', HyperItems.getEssence("tree"))
                .define('H', HyperItems.getEssence("herb"))
                .define('F', HyperItems.getEssence("food"))
                .define('M', HyperItems.getEssence("marine"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("garden")
                .pattern("L L L")
                .pattern("PLLLP")
                .pattern("PH HP")
                .pattern("PH HP")
                .pattern("PGGG!")
                .define('L', HyperItems.getEssence("light"))
                .define('P', HyperItems.getEssence("partition"))
                .define('H', HyperItems.getEssence("herb"))
                .define('G', HyperItems.getEssence("ground"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("wind")
                .pattern("   M ")
                .pattern("MMM!M")
                .pattern("   M ")
                .pattern(" PPP ")
                .pattern("PGGGP")
                .define('M', HyperItems.getEssence("motion"))
                .define('P', HyperItems.getEssence("partition"))
                .define('G', HyperItems.getEssence("ground"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("treasure")
                .pattern("BPPPB")
                .pattern("PMMMP")
                .pattern("Mm!mM")
                .pattern(" MmM ")
                .pattern("  M  ")
                .define('B', HyperItems.getEssence("battle"))
                .define('P', HyperItems.getEssence("partition"))
                .define('M', HyperItems.getEssence("mineral"))
                .define('m', HyperItems.getEssence("marine"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("flame")
                .pattern("L L L")
                .pattern("MLLLM")
                .pattern("LLMLL")
                .pattern("TLT!T")
                .pattern(" TTT ")
                .define('L', HyperItems.getEssence("light"))
                .define('M', HyperItems.getEssence("motion"))
                .define('T', HyperItems.getEssence("tree"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("frost")
                .pattern(" PMP ")
                .pattern("PMSMP")
                .pattern("MSFSM")
                .pattern("PMSMP")
                .pattern(" !MP ")
                .define('P', HyperItems.getEssence("partition"))
                .define('M', HyperItems.getEssence("marine"))
                .define('S', HyperItems.getEssence("shadow"))
                .define('F', HyperItems.getEssence("food"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("animal")
                .pattern("L L L")
                .pattern(" L L ")
                .pattern("LMLML")
                .pattern("MFMF!")
                .pattern("FMFMF")
                .define('L', HyperItems.getEssence("light"))
                .define('F', HyperItems.getEssence("food"))
                .define('M', HyperItems.getEssence("motion"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("monster")
                .pattern("S S S")
                .pattern(" S S ")
                .pattern("SMSMS")
                .pattern("!CMCM")
                .pattern("CMCMC")
                .define('S', HyperItems.getEssence("shadow"))
                .define('C', HyperItems.getEssence("crust"))
                .define('M', HyperItems.getEssence("motion"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("thunder")
                .pattern(" L L ")
                .pattern("SMLMS")
                .pattern(" LTL ")
                .pattern("SLTLS")
                .pattern(" !TS ")
                .define('L', HyperItems.getEssence("light"))
                .define('M', HyperItems.getEssence("motion"))
                .define('T', HyperItems.getEssence("tree"))
                .define('S', HyperItems.getEssence("sound"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("amusement")
                .pattern("SLSLS")
                .pattern("BSBSB")
                .pattern(" BSB ")
                .pattern("MMMM!")
                .pattern(" M M ")
                .define('S', HyperItems.getEssence("sound"))
                .define('L', HyperItems.getEssence("light"))
                .define('B', HyperItems.getEssence("battle"))
                .define('M', HyperItems.getEssence("motion"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("order")
                .pattern("FPFPF")
                .pattern("WPWPW")
                .pattern("WP!PW")
                .define('F', HyperItems.getEssence("food"))
                .define('W', HyperItems.getEssence("work"))
                .define('P', HyperItems.getEssence("partition"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("healing")
                .pattern(" HHH ")
                .pattern("DSDSD")
                .pattern(" FSF ")
                .pattern("DSD!D")
                .pattern(" MMM ")
                .define('H', HyperItems.getEssence("herb"))
                .define('D', HyperItems.getEssence("drawing"))
                .define('S', HyperItems.getEssence("sound"))
                .define('F', HyperItems.getEssence("food"))
                .define('M', HyperItems.getEssence("marine"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("echo")
                .pattern(" PPP ")
                .pattern("PsSsP")
                .pattern("PSs!P")
                .pattern("PsSsP")
                .pattern(" PPP ")
                .define('P', HyperItems.getEssence("partition"))
                .define('S', HyperItems.getEssence("shadow"))
                .define('s', HyperItems.getEssence("sound"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("death")
                .pattern(" SSS ")
                .pattern("SMPMS")
                .pattern("M!F M")
                .pattern(" PFP ")
                .pattern(" S S ")
                .define('S', HyperItems.getEssence("shadow"))
                .define('M', HyperItems.getEssence("motion"))
                .define('P', HyperItems.getEssence("partition"))
                .define('F', HyperItems.getEssence("food"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.core("wonder")
                .pattern("D D D")
                .pattern(" LSL ")
                .pattern("DS!SD")
                .pattern(" LSL ")
                .pattern("D D D")
                .define('D', HyperItems.getEssence("drawing"))
                .define('L', HyperItems.getEssence("light"))
                .define('S', HyperItems.getEssence("shadow"))
                .define('!', HyperItems.BUG_STARS.get(1).get())
                .saveMaterial(pWriter);

        DeskShapedRecipeBuilder.gist("contraption")
                .pattern(" EEEEE ")
                .pattern("EW  W E")
                .pattern("D W  W ")
                .pattern("DTTWMMW")
                .pattern("D W  W ")
                .pattern("EW  W E")
                .pattern(" EEEE! ")
                .define('E', HyperItems.getCore("echo"))
                .define('D', HyperItems.getEssence("drawing"))
                .define('W', HyperItems.getEssence("work"))
                .define('T', HyperItems.getEssence("tree"))
                .define('M', HyperItems.getEssence("mineral"))
                .define('!', HyperItems.BUG_STARS.get(2).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.gist("sky")
                .pattern(" WLLLW ")
                .pattern("WLW!WLW")
                .pattern("WTWMWFW")
                .pattern("W T F W")
                .pattern(" T M F ")
                .pattern("  T F  ")
                .pattern(" T M F ")
                .define('W', HyperItems.getCore("wind"))
                .define('T', HyperItems.getCore("thunder"))
                .define('F', HyperItems.getCore("frost"))
                .define('L', HyperItems.getEssence("light"))
                .define('M', HyperItems.getEssence("marine"))
                .define('!', HyperItems.BUG_STARS.get(2).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.gist("love")
                .pattern("  O O  ")
                .pattern(" DOOOD ")
                .pattern("DDaOaDD")
                .pattern("DDAHADD")
                .pattern(" DaO!D ")
                .pattern("  OOO  ")
                .pattern("   O   ")
                .define('O', HyperItems.getCore("order"))
                .define('D', HyperItems.getCore("death"))
                .define('a', HyperItems.getCore("amusement"))
                .define('A', HyperItems.getCore("animal"))
                .define('H', HyperItems.getCore("healing"))
                .define('!', HyperItems.BUG_STARS.get(2).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.gist("fear")
                .pattern(" CCCCC ")
                .pattern("CCSSSCC")
                .pattern("C!EEESC")
                .pattern("CEWWWEC")
                .pattern("CSEEESC")
                .pattern("CCSSSCC")
                .pattern(" CCCCC ")
                .define('C', HyperItems.getCore("cave"))
                .define('E', HyperItems.getCore("echo"))
                .define('W', HyperItems.getCore("wonder"))
                .define('S', HyperItems.getEssence("shadow"))
                .define('!', HyperItems.BUG_STARS.get(2).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.gist("adventure")
                .pattern("  TTT  ")
                .pattern("FFCMMMH")
                .pattern("FMFCWCM")
                .pattern("MFMMMCM")
                .pattern("MWFHCMC")
                .pattern("MFMLLLL")
                .pattern("HML!LTL")
                .define('T', HyperItems.getCore("treasure"))
                .define('C', HyperItems.getCore("cave"))
                .define('F', HyperItems.getCore("forest"))
                .define('L', HyperItems.getCore("land"))
                .define('W', HyperItems.getCore("wonder"))
                .define('H', HyperItems.getCore("healing"))
                .define('M', HyperItems.getEssence("motion"))
                .define('!', HyperItems.BUG_STARS.get(2).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.gist("taint")
                .pattern(" O   O ")
                .pattern("O S S O")
                .pattern("OSW WSO")
                .pattern("OWSWSWO")
                .pattern("O!DADDO")
                .pattern("ODAAADO")
                .pattern(" OOOOO ")
                .define('O', HyperItems.getCore("order"))
                .define('W', HyperItems.getCore("wonder"))
                .define('A', HyperItems.getCore("amusement"))
                .define('S', HyperItems.getEssence("sound"))
                .define('D', HyperItems.getEssence("drawing"))
                .define('!', HyperItems.BUG_STARS.get(2).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.gist("destruction")
                .pattern("AMMMMMA")
                .pattern(" AMMMA ")
                .pattern("  AMA  ")
                .pattern("   A   ")
                .pattern("P P P P")
                .pattern("P!PPPPP")
                .pattern("PPTTTPP")
                .define('M', HyperItems.getCore("monster"))
                .define('A', HyperItems.getCore("amusement"))
                .define('T', HyperItems.getCore("treasure"))
                .define('P', HyperItems.getEssence("partition"))
                .define('!', HyperItems.BUG_STARS.get(2).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.gist("leaping")
                .pattern("  OOO  ")
                .pattern(" OMMMO ")
                .pattern("OMWWWMO")
                .pattern("OMW WMO")
                .pattern("MW   WM")
                .pattern("MWG GWM")
                .pattern("MGGGGG!")
                .define('O', HyperItems.getCore("order"))
                .define('W', HyperItems.getCore("wind"))
                .define('G', HyperItems.getCore("garden"))
                .define('M', HyperItems.getEssence("motion"))
                .define('!', HyperItems.BUG_STARS.get(2).get())
                .saveMaterial(pWriter);
        DeskShapedRecipeBuilder.gist("fairy")
                .pattern(" H H H ")
                .pattern("H  F  H")
                .pattern(" F F F ")
                .pattern("WFFMFFW")
                .pattern(" FF!FF ")
                .pattern("W FFF W")
                .pattern(" W W W ")
                .define('H', HyperItems.getCore("healing"))
                .define('W', HyperItems.getCore("wonder"))
                .define('F', HyperItems.getCore("flame"))
                .define('M', HyperItems.getCore("monster"))
                .define('!', HyperItems.BUG_STARS.get(2).get())
                .saveMaterial(pWriter);

        new DeskShapelessRecipeBuilder(HyperItems.GAME_ORB.get())
                .values(HyperItems.GOD_SIGIL.get())
                .values(HyperItems.CHEMICAL_MAX.get())
                .values(HyperBlocks.SOUL.get().asItem())
                .values(HyperBlocks.FUMETSU_LEFT.get().asItem(), HyperBlocks.FUMETSU_SKULL.get().asItem(), HyperBlocks.FUMETSU_RIGHT.get().asItem())
                .values(HyperItems.BUG_STARS.stream().map(RegistryObject::get).toArray(Item[]::new))
                .values(ItemTags.create(identifier("essences")))
                .values(ItemTags.create(identifier("cores")))
                .values(ItemTags.create(identifier("gists")))
                .minecraft()
                .save(pWriter, identifier("game_orb"));
    }
}
